export const LABELS = {
  tickets: {
    title: 'Zgłoszenia',
    newTicket: 'Nowe zgłoszenie',
    notFound: 'Nie znaleziono zgłoszenia',
    backToList: 'Powrót do listy',
    loading: 'Ładowanie...',
    empty: 'Brak zgłoszeń',
    name: 'Zgłoszenie',
  },
  nav: {
    panel: 'Panel',
    tickets: 'Zgłoszenia',
    appName: 'Call Center',
    menu: 'Menu',
  },
  detail: {
    info: 'Informacje',
    description: 'Opis zgłoszenia',
    status: 'Status zgłoszenia',
    currentStatus: 'Aktualny status',
    save: 'Zapisz',
    back: 'Powrót',
    edit: 'Edytuj',
    ticketTitle: (id: string) => `Zgłoszenie #${id}`,
  },
  fields: {
    client: 'Klient',
    subject: 'Temat',
    priority: 'Priorytet',
    status: 'Status',
    createdAt: 'Data utworzenia',
    description: 'Opis',
  },
  form: {
    clientPlaceholder: 'Imię i nazwisko',
    subjectPlaceholder: 'Temat zgłoszenia',
    descriptionPlaceholder: 'Opis problemu',
    cancel: 'Anuluj',
    save: 'Zapisz',
    fillRequired: 'Wypełnij imię klienta i temat',
  },
  toast: {
    success: 'Sukces',
    error: 'Błąd',
    warning: 'Uwaga',
    ticketCreated: (subject: string) => `Zgłoszenie "${subject}" zostało utworzone`,
    ticketDeleted: (id: string) => `Zgłoszenie #${id} zostało usunięte`,
    statusUpdated: 'Status zgłoszenia został zaktualizowany',
    deleteConfirm: (id: string) => `Usunąć zgłoszenie #${id}?`,
    confirmHeader: 'Potwierdzenie',
    confirmDelete: 'Usuń',
    confirmCancel: 'Anuluj',
  },
  errors: {
    fetchTickets: 'Nie udało się pobrać zgłoszeń',
    fetchTicket: 'Nie udało się pobrać zgłoszenia',
    updateStatus: 'Nie udało się zaktualizować statusu',
    deleteTicket: 'Nie udało się usunąć zgłoszenia',
    createTicket: 'Nie udało się utworzyć zgłoszenia',
  },
  table: {
    id: 'ID',
    client: 'Klient',
    subject: 'Temat',
    status: 'Status',
    priority: 'Priorytet',
    date: 'Data',
    actions: 'Akcje',
    deleteAriaLabel: 'Usuń zgłoszenie',
  },
  validation: {
    customerNameRequired: 'Imię i nazwisko jest wymagane',
    customerNameMin: 'Imię i nazwisko musi mieć min. 2 znaki',
    subjectRequired: 'Temat jest wymagany',
    subjectMin: 'Temat musi mieć min. 3 znaki',
    descriptionRequired: 'Opis jest wymagany',
  },
} as const
